title: Fin's Silly Little Blog
description: Long Form Jekyll theme built with SASS, second version of Fin's Silly Little Blog

url: https://finny19.github.io/csci340lab5
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Interests
      url: /interests

social:
    github: finny19
    email: lockertfr@hendrix.edu

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
